// Code generated by hertz generator.

package user

import (
	"github.com/cloudwego/hertz/pkg/app"
	"hertz/demo/biz/middleware"
)

func rootMw() []app.HandlerFunc {
	return []app.HandlerFunc{middleware.AuthHandler}
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _hertzMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adminMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _useridMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _disableuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createuserMw() []app.HandlerFunc {
	// your code...
	return nil
}
