version: '3.7'
services:
  mysql:
    image: 'mysql:latest'
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=gorm
      - MYSQL_USER=gorm
      - MYSQL_PASSWORD=gorm
      - MYSQL_RANDOM_ROOT_PASSWORD="yes"
    networks:
      - hertz
  redis:
    image: 'redis:latest'
    ports:
      - "6379:6379"
    networks:
      - hertz
  server:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    networks:
      - hertz

networks:
  hertz:
    driver: bridge
