// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	handler "hertz/demo/biz/handler"

	"github.com/hertz-contrib/swagger"
	swaggerFiles "github.com/swaggo/files"
	_ "hertz/demo/internal/docs"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	// your code ...
	r.GET("/swagger/*any", swagger.WrapHandler(swaggerFiles.Handler))
}
