basePath: /
host: localhost:8888
info:
  contact: {}
  description: This is a demo using Hertz.
  license:
    name: Apache 2.0
  title: HertzTest
  version: "1.0"
paths:
  /v1/user/create:
    post:
      responses: {}
  /v1/user/delete/:user_id:
    post:
      responses: {}
  /v1/user/query:
    post:
      responses: {}
  /v1/user/update/:user_id:
    post:
      responses: {}
schemes:
- http
swagger: "2.0"
