basePath: /
host: localhost:8888
info:
  contact: {}
  description: This is a demo using Hertz.
  license:
    name: Apache 2.0
  title: HertzTest
  version: "1.0"
paths:
  /v1/im/admin/user:
    get:
      description: get user list
      responses:
        "200":
          description: OK
      tags:
      - user
    post:
      description: create user
      responses:
        "200":
          description: OK
      tags:
      - user
  /v1/im/admin/user/:userID:
    delete:
      description: delete user
      parameters:
      - description: user id
        in: path
        name: userID
        required: true
        type: integer
      responses:
        "200":
          description: OK
      tags:
      - user
  /v1/im/admin/user/:userID/disable:
    put:
      description: disable user
      parameters:
      - description: user id
        in: path
        name: userID
        required: true
        type: integer
      responses:
        "200":
          description: OK
      tags:
      - user
schemes:
- http
swagger: "2.0"
