// Code generated by hertz generator.

package ws

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _hertzMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _chatroomMw() []app.HandlerFunc {
	// your code...
	return nil
}
