// Code generated by hertz generator.

package oauth

import (
	"github.com/cloudwego/hertz/pkg/app"
	"hertz/demo/biz/middleware"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _hertzMw() []app.HandlerFunc {
	// your code...
	return nil
}

func __well_knownMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getjwksMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _auth2Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gettokenMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _imMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _auth20Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _logoutMw() []app.HandlerFunc {
	return []app.HandlerFunc{middleware.AuthHandler}
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginpasswordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginproviderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _meMw() []app.HandlerFunc {
	return []app.HandlerFunc{middleware.AuthHandler}
}

func _getprofileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateprofileMw() []app.HandlerFunc {
	// your code...
	return nil
}
