// Code generated by hertz generator.

package user

import (
	"context"
	"hertz/demo/biz/handler/internal"
	"hertz/demo/internal/response"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	user "hertz/demo/biz/model/hertz/user"
)

var a internal.Api

// GetUser .
// @Description	get user list
// @Tags		user
// @Success		200
// @router		/v1/im/admin/user [GET]
func GetUser(_ context.Context, c *app.RequestContext) {
	var req user.NULL
	if err := a.SetReqWithSub(c, &req).Error; err != nil {
		response.ErrorRequest(c, err)
		return
	}

	resp := new(user.CommonResp)

	c.JSON(consts.StatusOK, resp)
}

// CreateUser .
// @Description	create user
// @Tags		user
// @Success		200
// @router		/v1/im/admin/user [POST]
func CreateUser(_ context.Context, c *app.RequestContext) {
	var req user.CreateUserReq
	if err := a.SetReqWithSub(c, &req).Error; err != nil {
		response.ErrorRequest(c, err)
		return
	}

	resp := new(user.CommonResp)

	c.JSON(consts.StatusOK, resp)
}

// DisableUser .
// @Description	disable user
// @Tags		user
// @Param		userID		path	integer	true	"user id"
// @Success		200
// @router		/v1/im/admin/user/:userID/disable [PUT]
func DisableUser(_ context.Context, c *app.RequestContext) {
	var req user.UserReq
	if err := a.SetReqWithSub(c, &req).Error; err != nil {
		response.ErrorRequest(c, err)
		return
	}

	resp := new(user.CommonResp)

	c.JSON(consts.StatusOK, resp)
}

// DeleteUser .
// @Description	delete user
// @Tags		user
// @Param		userID		path	integer	true	"user id"
// @Success		200
// @router		/v1/im/admin/user/:userID [DELETE]
func DeleteUser(_ context.Context, c *app.RequestContext) {
	var req user.UserReq
	if err := a.SetReqWithSub(c, &req).Error; err != nil {
		response.ErrorRequest(c, err)
		return
	}

	resp := new(user.CommonResp)

	c.JSON(consts.StatusOK, resp)
}
